# Generated by Django 3.0.3 on 2020-04-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
